name: PR target test

on:
  pull_request_target:
    types:
      - opened
      - edited

jobs:
  code_review:
    runs-on: ubuntu-latest
    steps:
      - name: 👀 Checkout
        uses: actions/checkout@v2
      - name: cat readme
        run: cat ./readme.md
