name: PR target test

on:
  pull_request_target:
    types:
      - opened
      - edited

jobs:
  print-number:
    runs-on: ubuntu-latest
    steps:
      - name: ls
        run: ls ./
      - name: Print README.md
        run: cat ./readme.md
