name: PR target test

on:
  issue_comment:
    types: [created]

jobs:
  build:
      name: Build Canary
      if: github.event.issue.pull_request && contains(github.event.comment.body, '!canary')
  exec:
    name: Release Canary
        runs-on: ubuntu-latest
        needs: build
            steps:
              - name: Checkout Branch
                uses: actions/checkout@v3
                with:
                  fetch-depth: 1
                  ref: refs/pull/${{ github.event.issue.number }}/head
              - name: npm
                run: npm run build:cjs && npm run build:bootstrap
